plugins {
    java
    `java-library`
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }
}

java {
    withJavadocJar()
    withSourcesJar()
}

dependencies {
    implementation("net.minidev:accessors-smart:2.4.7")
    implementation("javax.activation:activation:1.1")
    implementation("org.apache.activemq:activemq-broker:5.16.0")
    implementation("org.apache.activemq:activemq-client:5.16.0")
    implementation("org.apache.activemq:activemq-jdbc-store:5.16.0")
    implementation("org.apache.activemq:activemq-kahadb-store:5.16.0")
    implementation("org.apache.activemq:activemq-openwire-legacy:5.16.0")
    implementation("org.apache.activemq.protobuf:activemq-protobuf:1.1")
    implementation("org.apache.activemq:activemq-ra:5.16.0")
    implementation("com.microsoft.azure:adal4j:1.0.0")
    implementation("splunk-otel-java:agent:2.19.0-SNAPSHOT")
    implementation("splunk-otel-java.testing:agent-test-extension:2.19.0-SNAPSHOT")
    implementation("org.eclipse.angus:angus-activation:1.0.0")
    implementation("org.codehaus.mojo:animal-sniffer-annotations:1.24")
    implementation("org.jetbrains:annotations:13")
    implementation("com.google.android:annotations:4.1.1.4")
    implementation("org.jetbrains:annotations:17.0.0")
    implementation("org.glassfish.hk2.external:aopalliance-repackaged:2.5.0-b44")
    implementation("org.apiguardian:apiguardian-api:1.1.2")
    implementation("org.ow2.asm:asm:9.8")
    implementation("org.glassfish.hk2.external:asm-all-repackaged:2.5.0-b44")
    implementation("org.ow2.asm:asm-analysis:9.8")
    implementation("org.ow2.asm:asm-commons:9.8")
    implementation("codes.rafael.asmjdkbridge:asm-jdk-bridge:0.0.10") 
    implementation("org.ow2.asm:asm-tree:9.8")
    implementation("org.ow2.asm:asm-util:9.8")
    implementation("org.assertj:assertj-core:3.27.4")
    implementation("com.google.auto:auto-common:1.2.1")
    implementation("com.google.auto.service:auto-service:1.1.1")
    implementation("rities.add("com.google.auto.service:auto-service-annotations:1.1.1")
    implementation("com.google.auto.value:auto-value:1.11.0")
    implementation("com.google.auto.value:auto-value-annotations:1.11.0")
    implementation("org.awaitility:awaitility:4.3.0")
    implementation("com.microsoft.azure:azure-core:0.9.3")
    implementation("com.microsoft.azure:azure-keyvault:0.9.3")
    implementation("org.bouncycastle:bcpkix-jdk18on:1.81")
    implementation("org.bouncycastle:bcprov-jdk15on:1.51")
    implementation("org.bouncycastle:bcprov-jdk18on:1.81")
    implementation("org.bouncycastle:bcutil-jdk18on:1.81")
    implementation("splunk-otel-java:bootstrap:2.19.0-SNAPSHOT")
    implementation("com.github.java-json-tools:btf:1.3")
    implementation("org.apache.bval:bval-jsr:2.0.5")
    implementation("net.bytebuddy:byte-buddy:1.17.6")
    implementation("net.bytebuddy:byte-buddy-agent:1.17.5")
    implementation("net.bytebuddy:byte-buddy-dep:1.17.6")
    implementation("org.checkerframework:checker-qual:3.43.0")
    implementation("org.glassfish.hk2:class-model:2.5.0-b44")
    implementation("io.github.classgraph:classgraph:4.8.154")
    implementation("com.fasterxml:classmate:1.1.0")
    implementation("org.openjdk.jmc:common:8.3.1")
    implementation("splunk-otel-java.testing:common:2.19.0-SNAPSHOT")
    implementation("org.glassfish.main.common:common-util:5")
    implementation("commons-beanutils:commons-beanutils:1.9.4")
    implementation("commons-cli:commons-cli:1.4")
    implementation("commons-codec:commons-codec:1.17.1")
    implementation("commons-collections:commons-collections:3.2.2")
    implementation("org.apache.commons:commons-collections4:4.4")
    implementation("org.apache.commons:commons-compress:1.27.1")
    implementation("org.apache.commons:commons-dbcp2:2.1")
    implementation("org.apache.commons:commons-digester3:3.2")
    implementation("commons-io:commons-io:2.19.0")
    implementation("org.apache.commons:commons-jexl3:3.4.0")
    implementation("commons-lang:commons-lang:2.6")
    implementation("org.apache.commons:commons-lang3:3.17.0")
    implementation("commons-logging:commons-logging:1.2")
    implementation("org.apache.commons:commons-math3:3.2")
    implementation("org.apache.commons:commons-pool2:2.6.0")
    implementation("org.apache.commons:commons-text:1.10.0")
    implementation("splunk-otel-java.instrumentation:compile-stub:2.19.0-SNAPSHOT")
    implementation("org.glassfish.hk2:config-types:2.5.0-b44")
    implementation("signalfx:csa-releases:25.7.0-1367")
    implementation("splunk-otel-java:custom:2.19.0-SNAPSHOT")
    implementation("org.testcontainers:database-commons:1.21.3")
    implementation("splunk-otel-java:dependencyManagement:2.19.0-SNAPSHOT")
    implementation("com.google.cloud.opentelemetry:detector-resources-support:0.36.0")
    implementation("com.lmax:disruptor:3.4.4")
    implementation("com.github.docker-java:docker-java-api:3.5.3")
    implementation("com.github.docker-java:docker-java-core:3.5.3")
    implementation("com.github.docker-java:docker-java-transport:3.5.3")
    implementation("com.github.docker-java:docker-java-transport-httpclient5:3.5.3")
    implementation("org.rnorth.duct-tape:duct-tape:1.0.8")
    implementation("org.owasp.encoder:encoder:1.2.3")
    implementation("com.google.errorprone:error_prone_annotations:2.36.0")
    implementation("com.google.guava:failureaccess:1.0.3")
    implementation("com.sun.xml.fastinfoset:FastInfoset:1.2.16")
    implementation("org.openjdk.jmc:flightrecorder:8.3.1")
    implementation("io.leangen.geantyref:geantyref:1.3.16")
    implementation("org.apache.geronimo.components:geronimo-connector:3.1.4")
    implementation("org.apache.geronimo.specs:geronimo-j2ee-connector_1.6_spec:1")
    implementation("org.apache.geronimo.javamail:geronimo-javamail_1.6_mail:1.0.0")
    implementation("org.apache.geronimo.components:geronimo-transaction:3.1.4")
    implementation("splunk-otel-java.instrumentation:glassfish:2.19.0-SNAPSHOT")
    implementation("org.glassfish.main.common:glassfish-api:5")
    implementation("org.glassfish.main.grizzly:grizzly-config:5")
    implementation("org.glassfish.grizzly:grizzly-framework:2.4.1")
    implementation("org.glassfish.grizzly:grizzly-http:2.4.1")
    implementation("org.glassfish.grizzly:grizzly-http-server:2.4.1")
    implementation("org.glassfish.grizzly:grizzly-http2:2.4.1")
    implementation("org.glassfish.grizzly:grizzly-portunif:2.4.1")
    implementation("org.apache.groovy:groovy:4.0.27")
    implementation("org.apache.groovy:groovy-bom:4.0.27")
    implementation("org.apache.groovy:groovy-json:4.0.27")
    implementation("io.grpc:grpc-api:1.74.0")
    implementation("io.grpc:grpc-bom:1.74.0")
    implementation("io.grpc:grpc-context:1.74.0")
    implementation("io.grpc:grpc-core:1.74.0")
    implementation("io.grpc:grpc-netty:1.74.0")
    implementation("io.grpc:grpc-util:1.74.0")
    implementation("com.google.code.gson:gson:2.11.0")
    implementation("com.google.guava:guava:33.4.8-jre")
    implementation("org.hamcrest:hamcrest:3")
    implementation("org.hamcrest:hamcrest-core:2.2")
    implementation("org.fusesource.hawtbuf:hawtbuf:1.11")
    implementation("org.hibernate:hibernate-validator:5.2.4.Final")
    implementation("org.glassfish.hk2:hk2:2.5.0-b44")
    implementation("org.glassfish.hk2:hk2-api:2.5.0-b44")
    implementation("org.glassfish.hk2:hk2-config:2.5.0-b44")
    implementation("org.glassfish.hk2:hk2-core:2.5.0-b44")
    implementation("org.glassfish.hk2:hk2-locator:2.5.0-b44")
    implementation("org.glassfish.hk2:hk2-runlevel:2.5.0-b44")
    implementation("org.glassfish.hk2:hk2-utils:2.5.0-b44")
    implementation("org.objectweb.howl:howl:1.0.1-1")
    implementation("org.hsqldb:hsqldb:2.3.2")
    implementation("org.apache.httpcomponents:httpclient:4.5.13")
    implementation("org.apache.httpcomponents.client5:httpclient5:5.5")
    implementation("org.apache.httpcomponents:httpcore:4.4.13")
    implementation("org.apache.httpcomponents.core5:httpcore5:5.3.4")
    implementation("org.apache.httpcomponents.core5:httpcore5-h2:5.3.4")
    implementation("com.sun.istack:istack-commons-runtime:3.0.8")
    implementation("com.ethlo.time:itu:1.7.0")
    implementation("com.google.j2objc:j2objc-annotations:3.0.0")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.19.2")
    implementation("com.fasterxml.jackson:jackson-bom:2.19.2")
    implementation("com.fasterxml.jackson.core:jackson-core:2.19.2")
    implementation("org.codehaus.jackson:jackson-core-asl:1.9.2")
    implementation("com.github.java-json-tools:jackson-coreutils:2")
    implementation("com.github.java-json-tools:jackson-coreutils-equivalence:1")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.19.2")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.19.2")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.19.2")
    implementation("org.codehaus.jackson:jackson-jaxrs:1.9.2")
    implementation("org.codehaus.jackson:jackson-mapper-asl:1.9.2")
    implementation("org.codehaus.jackson:jackson-xc:1.9.2")
    implementation("com.sun.activation:jakarta.activation:2.0.1")
    implementation("io.opentelemetry:opentelemetry-api:1.52.0")
    implementation("io.opentelemetry:opentelemetry-bom:1.52.0")
    implementation("io.opentelemetry:opentelemetry-bom-alpha:2.18.1-alpha")
    implementation("io.opentelemetry:opentelemetry-context:1.52.0")
    implementation("io.opentelemetry:opentelemetry-exporter-common:1.52.0")
    implementation("io.opentelemetry:opentelemetry-exporter-jaeger:1.52.0")
    implementation("io.opentelemetry:opentelemetry-exporter-jaeger-proto:1.52.0")
    implementation("io.opentelemetry:opentelemetry-exporter-logging:1.52.0")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp:1.52.0")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp-common:1.52.0")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp-http:1.52.0")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp-http-metrics:1.52.0")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp-http-trace:1.52.0")
    implementation("io.opentelemetry:opentelemetry-exporter-prometheus:1.52.0-alpha")
    implementation("io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations:2.18.1")
    implementation("io.opentelemetry.instrumentation:opentelemetry-instrumentation-api:2.18.1")
    implementation("io.opentelemetry.instrumentation:opentelemetry-instrumentation-api-semconv:2.18.1-alpha")
    implementation("io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom:2.18.1")
    implementation("io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:2.18.1-alpha")
    implementation("io.opentelemetry.javaagent:opentelemetry-javaagent:2.18.1")
    implementation("io.opentelemetry.javaagent:opentelemetry-javaagent-bootstrap:2.18.1-alpha")
    implementation("io.opentelemetry.javaagent:opentelemetry-javaagent-extension-api:2.18.1-alpha")
    implementation("io.opentelemetry.javaagent:opentelemetry-javaagent-internal-logging-simple:2.18.1-alpha")
    implementation("io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-jdbc:2.18.1-alpha")
    implementation("io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-servlet-2.2:2.18.1-alpha")
    implementation("io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-servlet-3.0:2.18.1-alpha")
    implementation("io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-servlet-common:2.18.1-alpha")
    implementation("io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-servlet-javax-common:2.18.1-alpha")
    implementation("io.opentelemetry.javaagent:opentelemetry-javaagent-tooling:2.18.1-alpha")
    implementation("io.opentelemetry.javaagent:opentelemetry-javaagent-tooling-java9:2.18.1-alpha")
    implementation("io.opentelemetry.javaagent:opentelemetry-muzzle:2.18.1-alpha")
    implementation("io.opentelemetry.proto:opentelemetry-proto:1.7.0-alpha")
    implementation("io.opentelemetry.contrib:opentelemetry-resource-providers:1.47.0-alpha")
    implementation("io.opentelemetry.contrib:opentelemetry-samplers:1.47.0-alpha")
    implementation("io.opentelemetry:opentelemetry-sdk:1.52.0")
    implementation("io.opentelemetry:opentelemetry-sdk-common:1.52.0")
    implementation("io.opentelemetry.instrumentation:opentelemetry-sdk-autoconfigure-support:2.18.1-alpha")
    implementation("io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:1.52.0")
    implementation("io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi:1.52.0")
    implementation("io.opentelemetry:opentelemetry-sdk-extension-incubator:1.52.0-alpha")
    implementation("io.opentelemetry:opentelemetry-sdk-extension-jaeger-remote-sampler:1.52.0")
    implementation("io.opentelemetry:opentelemetry-sdk-logs:1.52.0")
    implementation("io.opentelemetry:opentelemetry-sdk-metrics:1.52.0")
    implementation("io.opentelemetry:opentelemetry-sdk-testing:1.52.0")
    implementation("io.opentelemetry:opentelemetry-sdk-trace:1.52.0")
    implementation("io.opentelemetry.semconv:opentelemetry-semconv:1.34.0")
    implementation("io.opentelemetry.semconv:opentelemetry-semconv-incubating:1.34.0-alpha")
    implementation("io.opentelemetry.javaagent:opentelemetry-testing-common:2.18.1-alpha")
    implementation("org.opentest4j:opentest4j:1.3.0")
    implementation("org.apache.openwebbeans:openwebbeans-ee:2.0.12")
    implementation("org.apache.openwebbeans:openwebbeans-ee-common:2.0.12")
    implementation("org.apache.openwebbeans:openwebbeans-ejb:2.0.12")
    implementation("org.apache.openwebbeans:openwebbeans-el22:2.0.12")
    implementation("org.apache.openwebbeans:openwebbeans-impl:2.0.12")
    implementation("org.apache.openwebbeans:openwebbeans-spi:2.0.12")
    implementation("org.apache.openwebbeans:openwebbeans-web:2.0.12")
    implementation("io.perfmark:perfmark-api:0.27.0")
    implementation("splunk-otel-java:profiler:2.19.0-SNAPSHOT")
    implementation("io.prometheus:prometheus-metrics-config:1.3.8")
    implementation("io.prometheus:prometheus-metrics-exporter-common:1.3.8")
    implementation("io.prometheus:prometheus-metrics-exporter-httpserver:1.3.8")
    implementation("io.prometheus:prometheus-metrics-exposition-textformats:1.3.8")
    implementation("io.prometheus:prometheus-metrics-model:1.3.8")
    implementation("com.google.protobuf:protobuf-bom:4.31.1")
    implementation("com.google.protobuf:protobuf-java:4.31.1")
    implementation("com.google.protobuf:protobuf-java-util:4.31.1")
    implementation("com.google.protobuf:protoc:4.31.1")
    implementation("org.tomitribe.quartz:quartz:2.2.4")
    implementation("org.apache.openejb.shade:quartz-openejb-shade:2.2.4")
    implementation("org.mozilla:rhino:1.7.7.2")
    implementation("org.glassfish.main.common:scattered-archive-api:5")
    implementation("net.sourceforge.serp:serp:1.15.1")
    implementation("splunk-otel-java.instrumentation:servlet-3-testing:2.19.0-SNAPSHOT")
    implementation("org.mortbay.jetty:servlet-api:3.0.20100224")
    implementation("javax.servlet:servlet-api:2.2")
    implementation("io.prometheus:simpleclient:0.16.0")
    implementation("io.prometheus:simpleclient_common:0.16.0")
    implementation("io.prometheus:simpleclient_httpserver:0.16.0")
    implementation("io.prometheus:simpleclient_tracer_common:0.16.0")
    implementation("io.prometheus:simpleclient_tracer_otel:0.16.0")
    implementation("io.prometheus:simpleclient_tracer_otel_agent:0.16.0")
    implementation("org.slf4j:slf4j-api:2.0.17")
    implementation("org.slf4j:slf4j-jdk14:1.7.21")
    implementation("org.yaml:snakeyaml:2.4")
    implementation("org.snakeyaml:snakeyaml-engine:2.9")
    implementation("org.spockframework:spock-bom:2.4-M6-groovy-4.0")
    implementation("org.spockframework:spock-core:2.4-M6-groovy-4.0")
    implementation("org.spockframework:spock-junit4:2.4-M6-groovy-4.0")
    implementation("javax.xml.stream:stax-api:1.0-2")
    implementation("stax:stax-api:1.0.1")
    implementation("org.jvnet.staxex:stax-ex:1.8.1")
    implementation("io.swagger.core.v3:swagger-annotations:2.2.8")
    implementation("io.swagger:swagger-annotations:1.6.9")
    implementation("io.swagger:swagger-compat-spec-parser:1.0.64")
    implementation("io.swagger.core.v3:swagger-core:2.2.8")
    implementation("io.swagger:swagger-core:1.6.9")
    implementation("io.swagger.core.v3:swagger-models:2.2.8")
    implementation("io.swagger:swagger-models:1.6.9")
    implementation("io.swagger.parser.v3:swagger-parser:2.1.10")
    implementation("io.swagger:swagger-parser:1.0.64")
    implementation("io.swagger.parser.v3:swagger-parser-core:2.1.10")
    implementation("io.swagger.parser.v3:swagger-parser-v2-converter:2.1.10")
    implementation("io.swagger.parser.v3:swagger-parser-v3:2.1.10")
    implementation("org.codehaus.swizzle:swizzle-stream:1.6.2")
    implementation("org.metatype.sxc:sxc-jaxb-core:0.8")
    implementation("org.metatype.sxc:sxc-runtime:0.8")
    implementation("org.testcontainers:testcontainers:1.21.3")
    implementation("org.testcontainers:testcontainers-bom:1.21.3")
    implementation("org.jvnet:tiger-types:1.4")
    implementation("splunk-otel-java.instrumentation:tomcat:2.19.0-SNAPSHOT")
    implementation("org.apache.tomcat:tomcat-annotations-api:9.0.40")
    implementation("org.apache.tomcat:tomcat-api:9.0.40")
    implementation("org.apache.tomcat:tomcat-catalina:9.0.40")
    implementation("org.apache.tomcat:tomcat-coyote:9.0.40")
    implementation("org.apache.tomcat:tomcat-el-api:9.0.40")
    implementation("org.apache.tomcat:tomcat-jaspic-api:9.0.40")
    implementation("org.apache.tomcat:tomcat-jni:9.0.40")
    implementation("org.apache.tomcat:tomcat-jsp-api:9.0.40")
    implementation("org.apache.tomcat:tomcat-juli:9.0.40")
    implementation("org.apache.tomcat:tomcat-servlet-api:9.0.40")
    implementation("org.apache.tomcat:tomcat-util:9.0.40")
    implementation("org.apache.tomcat:tomcat-util-scan:9.0.40")
    implementation("splunk-otel-java.instrumentation:tomee:2.19.0-SNAPSHOT")
    implementation("org.glassfish.jaxb:txw2:2.3.2")
    implementation("com.github.java-json-tools:uri-template:0.1")
    implementation("javax.validation:validation-api:1.1.0.Final")
    implementation("org.apache.velocity:velocity-engine-core:2.3")
    implementation("org.apache.velocity:velocity-engine-scripting:2.3")
    implementation("org.apache.velocity.tools:velocity-tools-generic:3.1")
    implementation("splunk-otel-java.instrumentation:weblogic:2.19.0-SNAPSHOT")
    implementation("splunk-otel-java.instrumentation:websphere:2.19.0-SNAPSHOT")
    implementation("splunk-otel-java.instrumentation:wildfly:2.19.0-SNAPSHOT")
    implementation("org.wildfly.core:wildfly-version:13.0.0.Final")
    implementation("org.apache.xbean:xbean-asm7-shaded:4.14")
    implementation("org.apache.xbean:xbean-asm8-shaded:4.17")
    implementation("org.apache.xbean:xbean-bundleutils:4.14")
    implementation("org.apache.xbean:xbean-finder-shaded:4.14")
    implementation("org.apache.xbean:xbean-naming:4.14")
    implementation("org.apache.xbean:xbean-reflect:4.14")
    implementation("org.xmlunit:xmlunit-core:2.9.1")
    implementation("org.xmlunit:xmlunit-placeholders:2.9.1")
    implementation("io.zipkin.zipkin2:zipkin:2.27.1")
    implementation("io.zipkin.reporter2:zipkin-reporter:3.5.1")
    implementation("io.zipkin.reporter2:zipkin-sender-okhttp3:3.5.1")
}

// Define custom configurations for bootstrapLibs and upstreamAgent
val bootstrapLibs by configurations.creating
val upstreamAgent by configurations.creating
val isolateJavaagentLibs by tasks.register<Copy>("isolateJavaagentLibs") {
    from(bootstrapLibs, upstreamAgent)
    into(layout.buildDirectory.dir("javaagent-libs"))
}

tasks.jar {
    enabled = false
}

tasks.processResources {
    from(rootProject.file("licenses")) {
        into("META-INF/licenses")
    }
}

tasks.shadowJar {
    configurations = listOf(project.configurations.runtimeClasspath.get(), bootstrapLibs, upstreamAgent)
    dependsOn(tasks.named("isolateJavaagentLibs"))
    from(tasks.named("isolateJavaagentLibs").get().outputs)
    filesMatching("META-INF/licenses/licenses.md") {
        path = path.replace("licenses.md", "licenses-splunk-otel-java.md")
    }
    archiveClassifier.set("all")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(
            "Premain-Class" to "io.opentelemetry.javaagent.OpenTelemetryAgent",
            "Agent-Class" to "io.opentelemetry.javaagent.OpenTelemetryAgent",
            "Can-Retransform-Classes" to "true",
            "Can-Redefine-Classes" to "true"
        )
    }
}

// Example task to create a mainShadowJar (adjust as needed)
val mainShadowJar by tasks.register<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("mainShadowJar") {
    from(zipTree(tasks.shadowJar.get().archiveFile))
    archiveClassifier.set("main")
    manifest {
        attributes(tasks.shadowJar.get().manifest.attributes)
    }
}

tasks.build {
    dependsOn(tasks.shadowJar, mainShadowJar)
}
