version: 2.1

jobs:
  build:
    resource_class: xlarge
    docker:
      - image: datadog/dd-trace-java-docker-build:latest
        environment:
          JAVA_HOME: /usr/lib/jvm/zulu-11-amd64
    steps:
      - checkout
      - run:
          name: Build Project
          command: |
            ./gradlew clean build --scan --no-daemon

      - run:
          name: Collect Test Results
          when: always
          command: .circleci/collect_results.sh

workflows:
  PR:
    jobs:
      - build