name: Java Project

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  java-application-build:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_PROD }}

      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' 

      - name: Set truststore paths
        run: |
          echo "JAVA_CACERTS=$JAVA_HOME/lib/security/cacerts" >> $GITHUB_ENV
          echo "CUSTOM_CACERTS=/tmp/cacerts" >> $GITHUB_ENV

      - name: Copy default cacerts to a writable location
        run: cp "$JAVA_CACERTS" "$CUSTOM_CACERTS"

      - name: Import proxy cert into custom truststore
        run: |
          keytool -importcert \
            -noprompt \
            -trustcacerts \
            -alias custom-proxy \
            -file /etc/ssl/certs/pse.pem \
            -keystore "$CUSTOM_CACERTS" \
            -storepass changeit

      - name: Build with Gradle using custom truststore
        run: |
          ./gradlew build \
            -Djavax.net.ssl.trustStore="$CUSTOM_CACERTS" \
            -Djavax.net.ssl.trustStorePassword=changeit

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"

  gather_analytics:
   runs-on: ubuntu-latest
   name: Gather Analytics
   needs: java-application-build
   if: always()
   steps:
   - name: Gather Status
     uses: invisirisk/pse-action@latest
     with:
      api_url: "https://app.invisirisk.com"
      app_token: ${{ secrets.IR_API_KEY_PROD }}
      send_job_status: "true"
